version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - 8008:8008
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
      python manage.py migrate &&
       python manage.py runserver 0.0.0.0:8008"
    env_file:
         - .env
    depends_on:
      - db

      
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
         - '5432:5432'
    volumes:
         - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  static-data:
    