# Generated by Django 3.2.25 on 2024-09-02 23:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_csirt'),
    ]

    operations = [
        migrations.AddField(
            model_name='csirt',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.csirt_image_file_path),
        ),
    ]
