# Generated by Django 3.2.25 on 2026-03-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_csirt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='csirt',
            name='country',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='csirt',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
